import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "GodsEye International",
  description: "GE | GodsEye demonstrates the vulnerabilities of the digital world. Specializing in advanced information retrieval and digital access, we uncover the hidden truths behind modern privacy and security.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "GodsEye",
    "GodsEyeGroup",
    "react-icons",
    "cn",
    "clsx",
    "crypto",
    "GE",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "international",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "GodsEye",
    url: "mailto:godseyeinternational@proton.me",
  },
} as const;
